version: '2'
services:
  moodle:
    image: docker.io/bitnami/moodle:latest
    restart: always
    ports:
      - 80:8080
    environment:
      - MOODLE_DATABASE_HOST=rds.c4wznr5e5vio.us-east-1.rds.amazonaws.com
      - MOODLE_DATABASE_USER=admin
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - BITNAMI_DEBUG=true
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_PASSWORD=adminmoodle
    volumes:
      - '/mnt/moodle/moodle_data:/bitnami/moodle'
      - '/mnt/moodle/moodledata_data:/bitnami/moodledata'