# Constants....

PORT = 5000
ENCONDING_FORMAT = "utf-8"
RECV_BUFFER_SIZE = 2048
IP_SERVER = '127.0.0.1'
CREATE = 'CREATE'
LOAD = 'LOAD'
PING = 'PING'
PUT = 'PUT'
GET = 'GET'
SAVE = 'SAVE'
UPDATE = 'UPDATE'
EXIT = 'EXIT'
RESET = "RESET"
DELETE = 'DELETE'